import Head from 'next/head';
import React from 'react'

const Layout = ({children}) => {
  return (
      <div>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className="bg-gray-50 min-h-screen">
              <div>{children}</div>
          </main>
      </div>
  );
}

export default Layout